### ISSUE TITLE
issues trying to deploy css

### ISSUE THREAD

**Issue by speralta-burwood** [GoogleCloudPlatform/core-solution-services#69]
I am running into issues running this in the jumphost:
---
- Version is 1.17.11 not 1.17.12 when I was following the repo

---
- Beforre sb infra apply 2-foundation, I had to rename firestore_setup.tf line 42 in  2-foundation because of the error
- `Error creating Database: googleapi: Error 409: Database already exists. Please use another database_id`

---
- I did not place a custom domain and got this error will when applying sb deploy:
- `The ManagedCertificate "default-managed-cert" is invalid: spec.domainsp[0]: Invalid value: "null": spec.domains[0] in body must be of type string: "null" `
- `kubectl apply: exit status 1`	 

---
- I created another deployment and applied a domain ex. css-backend.tunedcold.site , and this error occurred
- `The ManagedCertificate "default-managed-cert" is invalid: spec.domainsp[0]: Invalid value: "null": spec.domains[0] in body should match '^(([a-z0-9]+|[a-z0-9][-a-z0-9]*[a-z0-9])\.)+[a-z][-a-z0-9]*[a-z0-9]$'`
- ` kubectl apply: exit status 1`	

---
- changed “localhost” to the domain in step sb components add terraform_gke_ingress and getting this error:
- `unable to connect to the server: dial tcp 34.41.14.233:443: i/o timeout .  `
- `kubectl apply: exit status 1`

---
- Waited for a bit, then stilll got the same error previously:
- ` - The ManagedCertificate "default-managed-cert" is invalid: spec.domains[1]: Invalid value: "localhost": spec.domains[1] in body should match '^(([a-z0-9]+|[a-z0-9][-a-z0-9]*[a-z0-9])\.)+[a-z][-a-z0-9]*[a-z0-9]$'`

I am trying to deploy this app and have been stuck in the step "sb deploy". I may be missiing something as I am following the readme.

**Comment by lavjain** [comment]
@speralta-burwood Please ignore ` Database already exists` error. For a ManagedCertificate we need an actual domain (`localhost` won't work)
